### PR TITLE
fix cancel create item manually

### LINKED ISSUE #665: Click Cancel in new item screen should skip creation of empty item
Currently it takes you back to the item details pane with an empty item, but we shouldn't create an item at all in this case

### PR DESCRIPTION
**Pull request by angiemugo**
Fixes #665

### CODE REVIEW

File: Zotero/Scenes/Detail/ItemDetail/ViewModels/ItemDetailActionHandler.swift [hunk 1]
```diff
@@ -780,6 +780,25 @@ struct ItemDetailActionHandler: ViewModelActionHandler, BackgroundDbProcessingAc
             return
         }
 
+        if case .creation = viewModel.state.type {
```
Comment (michalrentka) [inline Zotero/Scenes/Detail/ItemDetail/ViewModels/ItemDetailActionHandler.swift:783]: No need to duplicate the whole block, you can just change the `if` to `switch`:
```
switch viewModel.state.type {
case .duplication, .creation:
... just one deletion block here ...
default: break
}
```

File: Zotero/Scenes/Detail/ItemDetail/ViewModels/ItemDetailActionHandler.swift [hunk 2]
```diff
@@ -777,7 +778,8 @@ struct ItemDetailActionHandler: ViewModelActionHandler, BackgroundDbProcessingAc
                     state.hideController = true
                 }
             }
-            return
```
Comment (michalrentka) [inline Zotero/Scenes/Detail/ItemDetail/ViewModels/ItemDetailActionHandler.swift:780]: This `return` shouldn't be removed, there's no need to update the viewModel again below, since we're leaving the screen (`state.hideController = true`).

Comment (angiemugo) [reply Zotero/Scenes/Detail/ItemDetail/ViewModels/ItemDetailActionHandler.swift:780]: In that case, then I can put this piece of code in the last case of `viewModel.state.type`

Comment (michalrentka) [reply Zotero/Scenes/Detail/ItemDetail/ViewModels/ItemDetailActionHandler.swift:780]: Sure, that works too
