### PR TITLE
Fixed crash of remotely changed and updated document

### LINKED ISSUE #937: PDF Sync crash 1439304954
https://forums.zotero.org/discussion/114654/ios-crash-report-1439304954#latest

### PR DESCRIPTION
**Pull request by michalrentka**
Fixes #937

### CODE REVIEW

**Comment by michalrentka** [comment]
@dstillman can you check the error string and probably update it to something better?

File: Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift [hunk 1]
```diff
@@ -421,6 +421,14 @@ class PDFReaderViewController: UIViewController {
     // MARK: - Actions
 
     private func update(state: PDFReaderState) {
+        if state.changes.contains(.md5) {
+            DispatchQueue.main.async {
+                self.coordinatorDelegate?.showDocumentChangedAlert(key: state.key, parentKey: state.parentKey, libraryId: state.library.identifier)
+            }
+            close()
```
Comment (mvasilak) [inline Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift:428]: It might be better if either `close()` has a completion block that it passes to `dismiss` and in that  `showDocumentChangedAlert()` is called,
or even if `showDocumentChangedAlert()` has an action block parameter, that then calls `close()`.
In the latter case, there is no need to have the `DetailCoordinator.navigationController` present, and it seems less forced than just dismissing the current screen.

**Review by mvasilak — COMMENTED** [review]
Instead of just closing the reader, couldn't we offer an action to reload the document? That is, create a new `Document` (the `url` is the same) and set it to the document view controller child pdf view controller, which will trigger a reload. Of course other elements would need to be reloaded, such as page thumbnails, annotations, etc.

If that is feasible, I guess we can even make it a single action alert?

**Comment by michalrentka** [comment]
> Instead of just closing the reader, couldn't we offer an action to reload the document? That is, create a new `Document` (the `url` is the same) and set it to the document view controller child pdf view controller, which will trigger a reload. Of course other elements would need to be reloaded, such as page thumbnails, annotations, etc.
> 
> If that is feasible, I guess we can even make it a single action alert?

It is feasible, but it's quite a lot of work for a thing that doesn't really happen normally. I mean it's possible, but people don't usually just manually edit the PDF file stored in Zotero and add/remove pages from it. So if that happens I think just closing the document with an explanation is fine. If there are complaints we can improve this, but I wouldn't overdo it.

File: Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift (hunk 1 above)
Comment (michalrentka) [reply Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift]: Changed in bab66baa9ff2f21e76412a20c678189eb7f53680

File: Zotero/Scenes/Detail/PDF/ViewModels/PDFReaderActionHandler.swift [hunk 2]
```diff
@@ -1629,13 +1629,21 @@ final class PDFReaderActionHandler: ViewModelActionHandler, BackgroundDbProcessi
...
             }
 
-            let isDark = viewModel.state.interfaceStyle == .dark
             let key = viewModel.state.key
+            let (item, liveAnnotations, storedPage) = try loadItemAnnotationsAndPage(for: key, libraryId: viewModel.state.library.identifier)
+
+            if let url = viewModel.state.document.fileURL, let md5 = md5(from: url), item.backendMd5 != md5 {
+                update(viewModel: viewModel) { state in
+                    state.changes = .md5
+                }
```
Comment (mvasilak) [inline Zotero/Scenes/Detail/PDF/ViewModels/PDFReaderActionHandler.swift:1638]: This part is similar to `case .change` in nested function `observe` below. It can be refactored to a private method, or even better another nested function.

File: Zotero/Scenes/Detail/PDF/PDFCoordinator.swift [hunk 3]
```diff
@@ -36,6 +36,7 @@ protocol PdfReaderCoordinatorDelegate: AnyObject {
     func showFontSizePicker(sender: UIView, picked: @escaping (UInt) -> Void)
     func showDeleteAlertForAnnotation(sender: UIView, delete: @escaping () -> Void)
     func showTagPicker(libraryId: LibraryIdentifier, selected: Set<String>, userInterfaceStyle: UIUserInterfaceStyle?, picked: @escaping ([Tag]) -> Void)
+    func showDocumentChangedAlert(key: String, parentKey: String?, libraryId: LibraryIdentifier, completed: @escaping () -> Void)
```
Comment (mvasilak) [inline Zotero/Scenes/Detail/PDF/PDFCoordinator.swift:39]: The first parameters seem not to be used at all.

File: Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift [hunk 4]
```diff
@@ -421,6 +421,13 @@ class PDFReaderViewController: UIViewController {
     // MARK: - Actions
 
     private func update(state: PDFReaderState) {
+        if state.changes.contains(.md5) {
+            self.coordinatorDelegate?.showDocumentChangedAlert(key: state.key, parentKey: state.parentKey, libraryId: state.library.identifier) { [weak self] in
```
Comment (mvasilak) [inline Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift:425]: Remove `self`.

**Review by mvasilak — CHANGES_REQUESTED** [review]

File: Zotero/Scenes/Detail/PDF/PDFCoordinator.swift (hunk 3 above)
Comment (michalrentka) [reply Zotero/Scenes/Detail/PDF/PDFCoordinator.swift]: Removed in 9b5ebbbe2e66e8aa4763a6155777bfb0053b416e

File: Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift (hunk 4 above)
Comment (michalrentka) [reply Zotero/Scenes/Detail/PDF/Views/PDFReaderViewController.swift]: Removed in 9b5ebbbe2e66e8aa4763a6155777bfb0053b416e

**Review by mvasilak — APPROVED** [review]

**Comment by dstillman** [comment]
> "This document has been changed. You have to re-download it if you want to continue editing it."

@michalrentka: Does the alert appear before or after the reader closes?

**Comment by michalrentka** [comment]
> > "This document has been changed. You have to re-download it if you want to continue editing it."
> 
> @michalrentka: Does the alert appear before or after the reader closes?

@dstillman currently before, but I can change it to after.

**Comment by dstillman** [comment]
No, before is fine — just want to get the phrasing right.
